In [2]:
import numpy as np
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])
print("Original array:\n", arr)

Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("\nreturn every other elements from the entier array :", arr[::2])



return every other elements from the entier array : [1 3 5 7]


In [4]:
import numpy as np
arr = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18], [20, 2, 4], [6, 8, 10], [2, 4, -2.4], [1, 2, -1]])
print(arr[::2])
print(arr[::-2])


[[ 2.  4.  6.]
 [14. 16. 18.]
 [ 6.  8. 10.]
 [ 1.  2. -1.]]
[[ 1.  2. -1.]
 [ 6.  8. 10.]
 [14. 16. 18.]
 [ 2.  4.  6.]]


In [5]:
integers_array = np.array([1,2,3,4,5,6])
temp = integers_array[(integers_array > 2) & (integers_array < 5)]
print('Elements at indices (0,1), (1,2), (2,1), (2,2) : \n', temp)


Elements at indices (0,1), (1,2), (2,1), (2,2) : 
 [3 4]


In [6]:
arr = np.array([1,2,3,4,5,6])
temp = arr > 2
print("Elements greater than 2:\n", temp)


Elements greater than 2:
 [False False  True  True  True  True]


In [2]:
#integer array indexing
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices(0,3),(1,2),(2,1),""(3,0):\n",temp)


Elements at indices(0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


In [3]:
#boolean array indexing
cond=arr>2
#cond is a boolean array
temp=arr[cond]
print("Elements greater than 2:\n",temp)

Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [7]:
#joining two array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print("Original arrays\n",arr1,arr2)
print("Joined array:\n",arr)

Original arrays
 [1 2 3] [4 5 6]
Joined array:
 [1 2 3 4 5 6]


In [8]:
#horizontal join 
arr=np.hstack((arr1,arr2))
print("Horizontal joining:\n",arr)

Horizontal joining:
 [1 2 3 4 5 6]


In [9]:
#vertical join
arr=np.dstack((arr1,arr2))
print("Depth joining:\n",arr)

Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [10]:
#depth join
arr=np.dstack((arr1,arr2))
print("Depth joining:\n",arr)

Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print("\nOriginal Array:\n", arr)
print("\nSplitted array:\n", newarr)
#Displaying splitted array in another form
print("\nSplitted array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


Original Array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]

Splitted array in another form:

[1 2]
[3 4]
[5 6]
